# Generated by Django 4.0.3 on 2023-06-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_delete_answer_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comcomment',
            old_name='question',
            new_name='comwrite',
        ),
    ]
