# Generated by Django 4.0.3 on 2023-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_comcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcomment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comwrite',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
